/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java.lang.boot;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        AppTest classUnderTest = new AppTest();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
